env:
    node: true
    commonjs: true
    es6: true
    mocha: true
    browser: true
    es2021: true
extends: ['eslint:recommended', 'plugin:prettier/recommended']
parserOptions:
    ecmaVersion: "latest"

